name: Build Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    uses: geode-sdk/build-e2e/.github/workflows/build.yml@main
    with:
      bindings-ref: main
      cli-ref: main
      build-config: Release

  package:
    name: Package Mod
    uses: geode-sdk/build-e2e/.github/workflows/package.yml@main
    needs: build
