name: Build Mod

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          path: .
          build-config: Release

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: hiden-practice-percent
          path: build/*.geode
