name: Build Geode Mod (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

env:
  MOD_PATH: .   # Change si ton mod n'est pas à la racine

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          path: ${{ env.MOD_PATH }}
          build-config: RelWithDebInfo
          export-pdb: true
          bundle-pdb: true
          export-symbols: true

      - name: Upload .geode file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: "*.geode"
          retention-days: 30
